### ISSUE TITLE
[False] Messing with Soul Speed 3 causing false flags.

### ISSUE THREAD

**Issue by getxd-dev** [MWHunter/Grim#593]
**Describe the bug**
Messing with Soul Speed 3 and Soul Sand makes it false flag the player.

**To Reproduce**
https://getxd.me/content/grim.mp4

**Server Version:**
Paper 1.19

**Grim Version (Git commit or the version in the jar's name)**
Grim 2.3.9-all

**Relevant plugins**
None

**Comment by MWHunter** [comment]
I'll try to explain why I think this is sprinting desync

Last accurate tick
-0.1506760469076628 -0.13144198164057966

Horizontal friction on soul sand
0.6 * 0.91

After friction going into next tick:
-0.08226912161 -0.07176732197

Predicted:
-0.2631151133 0.0315975
distance to predicted movement = 0.160822

Actually:
-0.2220607 0.0077440855
distance to actual movement = 0.208302

Ratio of actual movement to predicted movement:
0.208302 / 0.160822 = ~1.295

Sprinting is 1.3x speed, rounding, floats, uncertainty, and trig tables could make this 1.295 instead of 1.3.

Difficult to know if this was sprinting desync, but will check if this is fixed after I fix https://github.com/MWHunter/Grim/issues/379

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/379
